// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VehicleGuard.Api.Infrastructure.Data;

#nullable disable

namespace VehicleGuard.Api.Infrastructure.Data.Migrations
{
    [DbContext(typeof(VehicleGuardDbContext))]
    [Migration("20260525223832_AddGpsAndVehicleEvent")]
    partial class AddGpsAndVehicleEvent
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VehicleGuard.Shared.Domain.Models.CommandLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Command")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(60)")
                        .HasColumnName("Command");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("getdate()");

                    b.Property<int>("EmbeddedDeviceId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("EmbeddedDeviceId");

                    b.Property<DateTime?>("RequestedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("RequestedAt");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(60)")
                        .HasColumnName("Status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedAt");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("UserId");

                    b.Property<int>("VehicleId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("VehicleId");

                    b.HasKey("Id");

                    b.HasIndex("EmbeddedDeviceId")
                        .HasDatabaseName("IX_CommandLogs_EmbeddedDeviceId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_CommandLogs_UserId");

                    b.HasIndex("VehicleId")
                        .HasDatabaseName("IX_CommandLogs_VehicleId");

                    b.ToTable("CommandLogs");
                });

            modelBuilder.Entity("VehicleGuard.Shared.Domain.Models.EmbeddedDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("getdate()");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedAt");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("VehicleId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("VehicleId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("VehicleId")
                        .IsUnique()
                        .HasDatabaseName("IX_EmbeddedDevice_VehicleId");

                    b.ToTable("EmbeddedDevices");
                });

            modelBuilder.Entity("VehicleGuard.Shared.Domain.Models.Gps", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("Int")
                        .HasColumnName("Age");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("EmbeddedDeviceId")
                        .HasColumnType("Int")
                        .HasColumnName("EmbeddedDeviceId");

                    b.Property<double>("Hdop")
                        .HasColumnType("float")
                        .HasColumnName("Hdop");

                    b.Property<double>("Latitude")
                        .HasColumnType("float")
                        .HasColumnName("Latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("float")
                        .HasColumnName("Longitude");

                    b.HasKey("Id");

                    b.HasIndex("EmbeddedDeviceId")
                        .HasDatabaseName("IX_Gps_EmbeddedDeviceId");

                    b.ToTable("Gps");
                });

            modelBuilder.Entity("VehicleGuard.Shared.Domain.Models.NotificationLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(500)")
                        .HasColumnName("Body");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("getdate()");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("SentAt");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(30)")
                        .HasColumnName("Status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(100)")
                        .HasColumnName("Title");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("UserId");

                    b.Property<int>("VehicleEventId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("VehicleEventId");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_NotificationLogs_UserId");

                    b.HasIndex("VehicleEventId")
                        .HasDatabaseName("IX_NotificationLogs_VehicleEventId");

                    b.ToTable("NotificationLogs");
                });

            modelBuilder.Entity("VehicleGuard.Shared.Domain.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(100)")
                        .HasColumnName("Email");

                    b.Property<string>("FcmToken")
                        .HasColumnType("NVARCHAR(255)")
                        .HasColumnName("FcmToken");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(100)")
                        .HasColumnName("PasswordHash");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedAt");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(60)")
                        .HasColumnName("Username");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_User_Email");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("VehicleGuard.Shared.Domain.Models.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(60)")
                        .HasColumnName("Brand");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(30)")
                        .HasColumnName("Color");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("getdate()");

                    b.Property<int>("EmbeddedDeviceId")
                        .HasColumnType("int");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(60)")
                        .HasColumnName("LicensePlate");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(60)")
                        .HasColumnName("Model");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedAt");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LicensePlate")
                        .IsUnique()
                        .HasDatabaseName("IX_Vehicle_LicensePlate");

                    b.HasIndex("UserId");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("VehicleGuard.Shared.Domain.Models.VehicleEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Classification")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(30)")
                        .HasColumnName("Classification");

                    b.Property<int>("EmbeddedDeviceId")
                        .HasColumnType("int")
                        .HasColumnName("EmbeddedDeviceId");

                    b.Property<int>("GpsId")
                        .HasColumnType("int")
                        .HasColumnName("GpsId");

                    b.Property<bool>("IsSensitivePeriod")
                        .HasColumnType("BIT")
                        .HasColumnName("IsSensitivePeriod");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("OccurredAt");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmbeddedDeviceId");

                    b.HasIndex("GpsId");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("IX_VehicleEvents_OccurredAt");

                    b.HasIndex("UserId");

                    b.ToTable("VehicleEvents");
                });

            modelBuilder.Entity("VehicleGuard.Shared.Domain.Models.CommandLog", b =>
                {
                    b.HasOne("VehicleGuard.Shared.Domain.Models.EmbeddedDevice", "EmbeddedDevice")
                        .WithMany("CommandLogs")
                        .HasForeignKey("EmbeddedDeviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_CommandLogs_EmbeddedDevice_EmbeddedDeviceId");

                    b.HasOne("VehicleGuard.Shared.Domain.Models.User", "User")
                        .WithMany("CommandLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_CommandLogs_User_UserId");

                    b.HasOne("VehicleGuard.Shared.Domain.Models.Vehicle", "Vehicle")
                        .WithMany("CommandLogs")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_CommandLogs_Vehicle_VehicleId");

                    b.Navigation("EmbeddedDevice");

                    b.Navigation("User");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("VehicleGuard.Shared.Domain.Models.EmbeddedDevice", b =>
                {
                    b.HasOne("VehicleGuard.Shared.Domain.Models.User", null)
                        .WithMany("EmbeddedDevices")
                        .HasForeignKey("UserId");

                    b.HasOne("VehicleGuard.Shared.Domain.Models.Vehicle", "Vehicle")
                        .WithOne("EmbeddedDevice")
                        .HasForeignKey("VehicleGuard.Shared.Domain.Models.EmbeddedDevice", "VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_EmbeddedDevice_Vehicle_VehicleId");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("VehicleGuard.Shared.Domain.Models.Gps", b =>
                {
                    b.HasOne("VehicleGuard.Shared.Domain.Models.EmbeddedDevice", "EmbeddedDevice")
                        .WithMany("Gps")
                        .HasForeignKey("EmbeddedDeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Gps_EmbeddedDevice_EmbeddedDeviceId");

                    b.Navigation("EmbeddedDevice");
                });

            modelBuilder.Entity("VehicleGuard.Shared.Domain.Models.NotificationLog", b =>
                {
                    b.HasOne("VehicleGuard.Shared.Domain.Models.User", "User")
                        .WithMany("NotificationLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_NotificationLogs_User_UserId");

                    b.HasOne("VehicleGuard.Shared.Domain.Models.VehicleEvent", "VehicleEvent")
                        .WithMany()
                        .HasForeignKey("VehicleEventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_NotificationLogs_VehicleEvent_VehicleEventId");

                    b.Navigation("User");

                    b.Navigation("VehicleEvent");
                });

            modelBuilder.Entity("VehicleGuard.Shared.Domain.Models.Vehicle", b =>
                {
                    b.HasOne("VehicleGuard.Shared.Domain.Models.User", "User")
                        .WithMany("Vehicles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Vehicles_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VehicleGuard.Shared.Domain.Models.VehicleEvent", b =>
                {
                    b.HasOne("VehicleGuard.Shared.Domain.Models.EmbeddedDevice", "EmbeddedDevice")
                        .WithMany("VehicleEvents")
                        .HasForeignKey("EmbeddedDeviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_VehicleEvents_EmbeddedDevice_EmbeddedDeviceId");

                    b.HasOne("VehicleGuard.Shared.Domain.Models.Gps", "Gps")
                        .WithMany()
                        .HasForeignKey("GpsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_VehicleEvents_Gps_GpsId");

                    b.HasOne("VehicleGuard.Shared.Domain.Models.User", null)
                        .WithMany("VehicleEvents")
                        .HasForeignKey("UserId");

                    b.Navigation("EmbeddedDevice");

                    b.Navigation("Gps");
                });

            modelBuilder.Entity("VehicleGuard.Shared.Domain.Models.EmbeddedDevice", b =>
                {
                    b.Navigation("CommandLogs");

                    b.Navigation("Gps");

                    b.Navigation("VehicleEvents");
                });

            modelBuilder.Entity("VehicleGuard.Shared.Domain.Models.User", b =>
                {
                    b.Navigation("CommandLogs");

                    b.Navigation("EmbeddedDevices");

                    b.Navigation("NotificationLogs");

                    b.Navigation("VehicleEvents");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("VehicleGuard.Shared.Domain.Models.Vehicle", b =>
                {
                    b.Navigation("CommandLogs");

                    b.Navigation("EmbeddedDevice")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
